[phases.setup]
nixPkgs = ['php82', 'php82Extensions.bcmath', 'php82Extensions.ctype', 'php82Extensions.curl', 'php82Extensions.dom', 'php82Extensions.fileinfo', 'php82Extensions.gd', 'php82Extensions.gmp', 'php82Extensions.mbstring', 'php82Extensions.openssl', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.zip']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
# Create necessary directories with proper permissions
cmds = [
    'mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache'
]

[start]
# Use bash to execute start script with proper permissions
cmd = 'bash start.sh'
