[phases.setup]
nixPkgs = ['php83', 'php83Extensions.bcmath', 'php83Extensions.ctype', 'php83Extensions.curl', 'php83Extensions.dom', 'php83Extensions.fileinfo', 'php83Extensions.gd', 'php83Extensions.gmp', 'php83Extensions.mbstring', 'php83Extensions.openssl', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.tokenizer', 'php83Extensions.xml', 'php83Extensions.zip']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
# Create necessary directories with proper permissions
cmds = [
    'mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache'
]

[start]
# Use bash to execute start script with proper permissions
cmd = 'bash start.sh'
