[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan view:clear && echo 'All caches cleared - starting server' && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
